# Generated by Django 3.2.11 on 2022-01-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
