# Generated by Django 3.2.11 on 2022-01-20 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_owner', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=25)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=300)),
                ('order_items', models.TextField()),
            ],
        ),
    ]
