# Generated by Django 3.2.11 on 2022-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
