# Generated by Django 3.2.11 on 2022-01-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
