# Generated by Django 3.2.11 on 2022-02-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='payment_method',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
