# Generated by Django 3.2.11 on 2022-01-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_basket'),
        ('bot', '0003_botuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.basket'),
        ),
    ]
