# Generated by Django 3.2.11 on 2022-01-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botuser_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='basket',
        ),
    ]
