# Generated by Django 3.2.11 on 2022-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_botuser_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='Address'),
        ),
    ]
